name: Create PR

on: push

jobs:
  extract-digest:
    name: Extract digest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Output ecr digest to output file
        id: ecr-output
        run: |
          echo "latest: digest: sha256:408utq034utw0349tugosjhgaw489ufoai4jfa size: 1161" >> output
  show-sha:
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.output-sha.outputs.SHORT_SHA_OUTPUT}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: output sha
        id: output-sha
        run: |
          SHORT_SHA_TEMP=$(echo ${{ github.sha }} | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA_TEMP" >> $GITHUB_ENV
          echo "SHORT_SHA_OUTPUT=$SHORT_SHA_TEMP" >> $GITHUB_OUTPUT

      - name: get env
        run: |
          echo $SHORT_SHA
  get-env:
    runs-on: ubuntu-latest
    needs: show-sha
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: get env prev section
        run: |
          echo "${{needs.show-sha.outputs.short-sha}}"

  change-other-repo:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    steps:
      - name: checkout other repo
        uses: actions/checkout@v3
        with:
          repository: Cojiroooo/github-actions-sub

      - name: create new file
        run: |
          echo "created by github actions" >> text.txt

      - name: get current date
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATE=$(date + '%Y-%m-%d')" >> $GITHUB_ENV

      - name: echo current date
        run: echo ${{ env.CURRENT_DATE }}

      # - name: create pr
      #   run: |
      #     gh pr create \
      #     --head "new_branch" \
      #     --base "main" \
      #     --title "pr created by github acitions" \
      #     --body "body"
      - name: create pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
             update(stage): update image tag
          commiter: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: release/update-image-tag-${{CURRENT_DATE}}
          base: main
          delete-branch: true
          title: |
            release(staging): update image tag at ${{ env.CURRENT_DATE }}
          body: |
            THIS PR IS AUTO GENERATED BY GITHUB ACTIONS IN https://github.com/Cojiroooo/github-actions-main
          draft: false
