name: Create PR

on: push

jobs:
  extract-digest:
    name: Extract digest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Output ecr digest to output file
        id: ecr-output
        run: |
          echo "latest: digest: sha256:408utq034utw0349tugosjhgaw489ufoai4jfa size: 1161" >> output
  show-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: output sha
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: get env
        run: |
          echo $SHORT_SHA
  get-env:
    runs-on: ubuntu-latest
    needs: show-sha
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: get env prev section
        run: |
          echo $SHORT_SHA
