name: Create PR by Create pr bot

on: push

jobs:
  create-pr:
    name: Create pull requests
    runs-on: ubuntu-latest

    steps:
      - name: checkout other repo
        uses: actions/checkout@v3
        with:
          repository: Cojiroooo/github-actions-sub
          ssh-key: ${{ secrets.PUSH_TO_GITHUB_ACTIONS_SUB }}

      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.CREATE_PR_BOT_APP_ID }}
          private_key: ${{ secrets.CREATE_PR_BOT_PRIVATE_KEY }}

      - name: create new file
        run: |
          echo "created by github actions" >> text1.txt

      - name: create pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: |
             update(stage): update image tag
          commiter: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: release/bot-update-image-tag-${{ env.CURRENT_DATE }}
          base: main
          delete-branch: true
          title: |
            release(staging): update image tag at ${{ env.CURRENT_DATE }}
          body: |
            THIS PR IS AUTO GENERATED BY GITHUB ACTIONS IN https://github.com/Cojiroooo/github-actions-main
          draft: false
